Handle profile command
webuild-community/core pull request #10
Opened 2021-06-11 16:03 UTC by ldhnam

Issue #7

2021-06-13 07:39 UTC, kurojs approved these changes

2021-06-13 07:39 UTC, kurojs commented on handler/command.go
> +		if err == gorm.ErrRecordNotFound {
This should be, `errors.Is(err, gorm.ErrRecordNotFound)` cause the error has been wrapped

2021-06-13 07:39 UTC, kurojs commented on service/event/slack.go
> +		if err == gorm.ErrRecordNotFound {
Check my previous comment ^

2021-06-16 12:39 UTC, lmquang requested changes

2021-06-16 12:39 UTC, lmquang commented on service/event/slack.go
> +func NewSlackService(logger *zap.Logger, db *gorm.DB, client *slack.Client, userSvc user.Service) Service {
e đừng import userSvc, vì nếu các svc import nhau sẽ bị lỗi import cycle, e xài db để query user

2021-06-16 12:39 UTC, lmquang commented on handler/command.go
>  		return c.NoContent(http.StatusNotFound)
return Status internal server error

2021-06-17 09:04 UTC, lmquang approved these changes

2021-06-17 09:04 UTC, merged